- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi


- id: 201
  key: digibyte
  currency: dgb
  fixed: 8
  fee: 2
  inuse: true
  type: WithdrawChannelDigibyte
